#!/bin/sh

# Feed this script a link and it will give dmenu
# some choice programs to use to open it.

case "$(printf "mpv\\nbrowser\\ncopy url\\nw3m" | dmenu -p "Open link with what program?")" in
	mpv) mpv -quiet "$1" ;;
	browser) "$BROWSER" "$1" > /dev/null;;
	"copy url") echo "$1" | xclip -selection clipboard ;;
	w3m) w3m "$1";;
esac
