#!/bin/sh

# A script to list directory in  a give path and them after chosing one opening them in alacritty.

find "$1" -xdev -maxdepth 1 -type d | dmenu -l 5 | xargs -I {} alacritty --working-directory {}
