#!/bin/sh

# kill those pesky proceses

source $HOME/.config/dmenu/config

selected=$(ps --user "$USER" -F | $DMENU -p "Select procces to kill:" -l 5 | awk '{print $2" "$11}')

[ -n "$selected" ] || exit

answer=$(printf "yes\\nno" | $DMENU -p "Are you sure?")

[ $answer = "yes" ] || exit

kill -9 "${selected%% *}"

quick-notify "Killed Procces" "$selected"
