#!/bin/sh

# simple power menu script

source $HOME/.config/dmenu/config

case "$(printf "shutdown\\nreboot" | $DMENU -p "Choose your poison")" in
    "shutdown") sudo poweroff ;;
    "reboot") sudo reboot ;;
esac
