#!/bin/bash

# dmenu script to run one of my most runned programs

source $HOME/.config/dmenu/config

declare -a software=(
    "bitwarden-desktop"
    "megasync"
    "spotify"
    "discord"
)

choice=$(printf "%s\n" "${software[@]}" | $DMENU -p "Choose software to run")

[ -n $choice ] || exit

$choice
