#!/bin/bash

declare -a Games=(
    "Heroic (Launcher)"
    "Lutris (Launcher)"
)

case "$(printf "%s\n" "${Games[@]}" | dmenu -p "Choose your game")" in
	  "Heroic (Launcher)") heroic ;;
    "Lutris (Launcher)") lutris ;;
esac
