#!/bin/sh

# script to run a menu prompt when having more than 2 players since
# playerctl is bad at managing more than one player at the same time

command="$@"
instances=$(playerctl -l | wc -l)

if [ "$instances" = "0" ]; then
    exit
elif [ "$instances" -lt "2" ]; then
    playerctl $command
else
    choice=$(playerctl -l | dmenu -p 'Manage:')
    playerctl -p $choice $command
fi
