#!/bin/sh

# It lets you choose the kind of screenshot to take, including
# copying the image or even highlighting an area to copy.

source $HOME/.config/dmenu/config

dir="$HOME/Pictures/screenshots"
[ ! -d "$dir" ] && mkdir $dir -p

case "$(printf "a selected area\\ncurrent window\\nfull screen\\na selected area (copy)\\ncurrent window (copy)\\nfull screen (copy)" | $DMENU -l 6 -p "Screenshot which area?")" in
    "a selected area") sleep 0.5; maim -s $dir/pic-selected-"$(date '+%y%m%d-%H%M-%S').png" ;;
    "current window") sleep 0.5; maim -i "$(xdotool getactivewindow)" $dir/pic-window-"$(date '+%y%m%d-%H%M-%S').png" ;;
    "full screen") sleep 0.5; maim $dir/pic-full-"$(date '+%y%m%d-%H%M-%S').png" ;;
    "a selected area (copy)") sleep 0.5; maim -s | xclip -selection clipboard -t image/png ;;
    "current window (copy)") sleep 0.5; maim -i "$(xdotool getactivewindow)" | xclip -selection clipboard -t image/png ;;
    "full screen (copy)") sleep 0.5; maim | xclip -selection clipboard -t image/png ;;
esac
