#!/bin/bash

# dmenu script to run one of my most runned programs

declare -a software=(
    "bitwarden-desktop"
    "megasync"
    "spotify"
    "discord"
)

choice=$(printf "%s\n" "${software[@]}" | dmenu -p "Choose software to run")

[ -n $choice ] || exit

$choice
